services:
  online-cv-api:
    environment:
      - TOKEN_GITHUB
    container_name: online-cv-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3000:3000